import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../../services/api";
import { useLanguage } from "../../i18n/LanguageContext";
import "./ThreatIntelDashboard.css";
const statusMeta = { healthy: ["Live", "●"], degraded: ["Curated", "◐"], failed: ["Unavailable", "○"], manual: ["Manual", "◐"] };
const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
function formatDate(value) { if (!value) return "—"; const d = new Date(value); return Number.isNaN(d.getTime()) ? "—" : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(d); }
function ThreatIntelDashboard() {
  const { language } = useLanguage(); const te = language === "te";
  const [health, setHealth] = useState(null); const [threats, setThreats] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState(null);
  useEffect(() => { let active = true; Promise.all([apiRequest("/intelligence/health"), apiRequest("/threats?limit=12")]).then(([h, t]) => { if (active) { setHealth(h); setThreats(t.threats || []); } }).catch((e) => active && setError(e.message || (te ? "ఇంటెలిజెన్స్ డ్యాష్‌బోర్డ్ లోడ్ కాలేదు." : "Unable to load the intelligence dashboard."))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [te]);
  const sorted = useMemo(() => [...threats].sort((a, b) => (severityOrder[a.severity] ?? 9) - (severityOrder[b.severity] ?? 9) || String(b.publishedAt || b.retrievedAt || "").localeCompare(String(a.publishedAt || a.retrievedAt || ""))), [threats]);
  const summary = health?.summary || {}; const live = (health?.feeds || []).filter((f) => f.status === "healthy").length; const curated = (health?.feeds || []).filter((f) => f.status === "manual" || f.status === "degraded").length;
  return <section className="intel-page"><header className="intel-hero"><div><span className="intel-eyebrow">CYBERRAKSHAK 2.0 · {te ? "ఇంటెలిజెన్స్ సెంటర్" : "INTELLIGENCE CENTER"}</span><h1>{te ? <>సిగ్నల్ <span>ఎక్కడి నుంచి వచ్చిందో తెలుసుకోండి.</span></> : <>Know <span>where the signal comes from.</span></>}</h1><p>{te ? "ఏ ఇంటెలిజెన్స్ ఫీడ్ లైవ్‌లో ఉందో, ఏ సమాచారం క్యూయరేట్ చేయబడిందో మరియు ఏ థ్రెట్‌కు మీ దృష్టి అవసరమో చూడండి." : "See which intelligence feeds are live, which records are curated, and why a threat deserves your attention."}</p></div><div className="intel-hero-actions"><Link className="intel-primary" to="/check">{te ? "మెసేజ్ చెక్ చేయండి →" : "Check a message →"}</Link><Link className="intel-secondary" to="/threats">{te ? "థ్రెట్ రాడార్" : "Threat Radar"}</Link></div></header>
  {error && <div className="intel-error" role="alert">⚠️ {error}</div>}<div className="intel-metrics"><article><span>{te ? "ఫీడ్ ఆరోగ్యం" : "Feed health"}</span><strong>{summary.healthPercent ?? 0}%</strong><small>{summary.healthy ?? 0} {te ? "సరిగ్గా ఉన్నాయి" : "healthy"} · {summary.failed ?? 0} {te ? "విఫలమయ్యాయి" : "failed"}</small></article><article><span>{te ? "లైవ్ ఫీడ్‌లు" : "Live feeds"}</span><strong>{live}</strong><small>{te ? "ఆటోమేటిక్‌గా రిఫ్రెష్ అయ్యే వనరులు" : "Automatically refreshed sources"}</small></article><article><span>{te ? "క్యూయరేట్ ఫీడ్‌లు" : "Curated feeds"}</span><strong>{curated}</strong><small>{te ? "స్పష్టంగా లేబుల్ చేసిన మాన్యువల్ వనరులు" : "Clearly labelled manual sources"}</small></article><article><span>{te ? "కనిపించే థ్రెట్‌లు" : "Visible threats"}</span><strong>{threats.length}</strong><small>{te ? "ప్రస్తుత ఫీడ్‌లోని రికార్డులు" : "Records in the current feed"}</small></article></div>
  <div className="intel-grid"><section className="intel-panel feed-panel"><div className="intel-panel-heading"><div><span className="panel-kicker">{te ? "మూల ఆధారం" : "PROVENANCE"}</span><h2>{te ? "వనరుల ఆరోగ్యం" : "Source health"}</h2></div><span className="generated">{te ? "అప్‌డేట్:" : "Updated"} {health?.generatedAt ? formatDate(health.generatedAt) : "—"}</span></div>{loading ? <div className="intel-loading">{te ? "వనరుల స్థితి లోడ్ అవుతోంది…" : "Loading source status…"}</div> : <div className="feed-list">{(health?.feeds || []).map((feed) => { const meta = statusMeta[feed.status] || statusMeta.degraded; return <article className="feed-row" key={feed.id}><div className={`feed-status status-${feed.status}`}><span>{meta[1]}</span></div><div className="feed-main"><strong>{feed.name || feed.sourceId}</strong><span>{feed.type || "intelligence"} · {feed.parser || "manual"}</span>{feed.url ? <a href={feed.url} target="_blank" rel="noreferrer" className="feed-link">{te ? "అధికారిక వనరు ↗" : "Official source ↗"}</a> : <span>{te ? "వనరు URL నమోదు కాలేదు" : "No source URL registered"}</span>}</div><div className="feed-state"><strong>{te ? ({ Live: "లైవ్", Curated: "క్యూయరేట్", Manual: "మాన్యువల్", Unavailable: "అందుబాటులో లేదు" }[meta[0]] || meta[0]) : meta[0]}</strong><span>{feed.records ?? 0} {te ? "రికార్డులు" : `record${feed.records === 1 ? "" : "s"}`}</span></div></article>; })}</div>}<p className="provenance-note">{te ? "‘లైవ్’ అంటే ఆటోమేటెడ్ పార్సర్ పనిచేస్తోందని మాత్రమే. ‘క్యూయరేట్’ అంటే రికార్డులు మాన్యువల్‌గా నిర్వహించబడుతున్నాయని అర్థం. ఏ లేబుల్ కూడా వనరు తప్పులేనిదని హామీ ఇవ్వదు." : "“Live” means the current integration has a working automated parser. “Curated” means the source is registered but its records are maintained manually. Neither label means a source is infallible."}</p></section>
  <section className="intel-panel methodology-panel"><span className="panel-kicker">{te ? "ట్రస్ట్ మోడల్" : "TRUST MODEL"}</span><h2>{te ? "థ్రెట్‌ను ఎలా చదవాలి" : "How to read a threat"}</h2>{[["01", te ? "వనరు" : "Source", te ? "సమాచారం ఎవరు ప్రచురించారో, అది అధికారిక వనరా కాదా చూడండి." : "Identify who published the information and whether the source is authoritative."],["02", te ? "ధృవీకరణ" : "Verification", te ? "ప్రచురించిన ఇంటెలిజెన్స్‌ను నిర్ధారించిన ఘటనగా భావించకండి." : "Separate published intelligence from a confirmed incident or definitive attribution."],["03", te ? "నిర్ణయం" : "Decision", te ? "ఆధారాలను ఉపయోగించి ఏం చెక్ చేయాలి, బ్లాక్ చేయాలి, రిపోర్ట్ చేయాలి లేదా నేర్చుకోవాలో నిర్ణయించండి." : "Use the evidence to decide what to check, block, report, or learn next."]].map(([n, title, text]) => <div className="trust-step" key={n}><b>{n}</b><div><strong>{title}</strong><span>{text}</span></div></div>)}<Link className="method-link" to="/threats">{te ? "థ్రెట్ రికార్డులు చూడండి →" : "Explore threat records →"}</Link></section></div>
  <section className="intel-panel records-panel"><div className="intel-panel-heading"><div><span className="panel-kicker">{te ? "తాజా సంకేతాలు" : "LATEST SIGNALS"}</span><h2>{te ? "థ్రెట్ రికార్డులు" : "Threat records"}</h2></div><Link to="/threats">{te ? "పూర్తి రాడార్ →" : "Open full radar →"}</Link></div>{loading ? <div className="intel-loading">{te ? "థ్రెట్ రికార్డులు లోడ్ అవుతున్నాయి…" : "Loading threat records…"}</div> : sorted.length === 0 ? <div className="intel-empty">{te ? "ప్రస్తుత క్యాటలాగ్‌లో థ్రెట్ రికార్డులు లేవు." : "No threat records are available in the current catalog."}</div> : <div className="record-grid">{sorted.map((threat) => <button className={`record-card severity-${threat.severity || "info"}`} key={threat.threatId || threat.id} onClick={() => setSelected(threat)}><div className="record-top"><span>{String(threat.severity || "info").toUpperCase()}</span><small>{threat.category || "general"}</small></div><h3>{threat.title}</h3><p>{threat.description}</p><footer><span>{threat.sourceConfidence ?? 0}% {te ? "నమ్మకం" : "confidence"}</span><span>{formatDate(threat.publishedAt || threat.retrievedAt)}</span></footer></button>)}</div>}</section>
  {selected && <div className="intel-modal-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="intel-modal" role="dialog" aria-modal="true" aria-label={selected.title} onClick={(e) => e.stopPropagation()}><button className="intel-close" onClick={() => setSelected(null)} aria-label="Close">×</button><span className={`record-severity severity-${selected.severity || "info"}`}>{String(selected.severity || "info").toUpperCase()}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="modal-facts"><div><span>{te ? "కేటగిరీ" : "Category"}</span><strong>{selected.category || "General"}</strong></div><div><span>{te ? "నమ్మకం" : "Confidence"}</span><strong>{selected.sourceConfidence ?? 0}%</strong></div><div><span>{te ? "ప్రచురణ" : "Published"}</span><strong>{formatDate(selected.publishedAt)}</strong></div><div><span>{te ? "సేకరణ" : "Retrieved"}</span><strong>{formatDate(selected.retrievedAt)}</strong></div></div><h3>{te ? "వనరు ఆధారం" : "Source provenance"}</h3><div className="modal-sources">{(selected.sources || []).map((s) => <div key={s.id || s.name}><strong>{s.name}</strong><span>Tier {s.tier ?? "—"} · {s.confidence ?? 0}% confidence</span></div>)}{(selected.sources || []).length === 0 && <span>{te ? "ఈ రికార్డుకు వనరు మెటాడేటా లేదు." : "No source metadata was attached to this record."}</span>}</div><Link className="intel-primary" to="/check">{te ? "సంబంధిత కంటెంట్ చెక్ చేయండి →" : "Check related content →"}</Link></article></div>}</section>;
}
export default ThreatIntelDashboard;
