name: CyberRakshak CI

on:
  push:
    branches:
      - main

jobs:
  backend-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Check server syntax
        run: |
          cd backend
          node -c server.js